services:
  database:
    image: mysql:8.0
    container_name: demo-database
    environment:
      - MYSQL_ROOT_PASSWORD=Sagor1234
      - MYSQL_DATABASE=sagor
      - MYSQL_USER=sagor1
      - MYSQL_PASSWORD=Sagors1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bizbooker-network
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 20s  # Give MySQL extra time to initialize
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demo-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/sagor
      - SPRING_DATASOURCE_USERNAME=sagor1
      - SPRING_DATASOURCE_PASSWORD=Sagor1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FRONTEND_URL=http://57.158.25.224:3000
      - SERVER_PORT=8080
      - STRIPE_SECRET_KEY=sk_test_51RnhaQP2ulg6Kx9Xdet2cf2FYRZYS6UA4qBYzjktoBpTORFulIIvwnr0xBoVbVGIg4v0XL29Op755eWoQ7p8RwLs00pC4l5V9g
      - STRIPE_PUBLISHABLE_KEY=pk_test_51RnhaQP2ulg6Kx9X35eE0YpD9NRJZOvjawqXlAKeKr3x7fOsXOvXA2B6sys8RlhfyHsGkd2DjshKJHqmlZOhv25500yze3lVy0
      - OPENAI_API_KEY=AIzaSyD3-sdrHhqyk4AAqIl-tYk9zrttg1sWY9E
    depends_on:
      database:
        condition: service_healthy
    networks:
      - bizbooker-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: demo-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - bizbooker-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  bizbooker-network:
    driver: bridge